#
#
#

all:

upload:
	scp green.png green-16x16.png brown.png headache.hungry.com:public_html/hifi/
	scp icons/*.svg headache.hungry.com:public_html/hifi/terrain/
	scp voxel-ground-utils.js voxels.js headache.hungry.com:public_html/hifi/
