#
#
#

all:
	(cd picture-c && make upload)

clean:
	rm -f *~
	(cd frame-0 && make clean)
	(cd frame-1 && make clean)
	(cd frame-2 && make clean)
	(cd picture-c && make clean)
	(cd picture-f && make clean)
	(cd picture-i && make clean)
	(cd picture-n && make clean)
	(cd picture-s && make clean)
	(cd picture-u && make clean)
