#
#
#

all:
	(cd picture-c && make upload)

clean:
	rm -f *~
	(cd frame-0 && make clean)
	(cd frame-1 && make clean)
	(cd picture-c && make clean)
	(cd picture-f && make clean)
	(cd picture-u && make clean)
