#+TITLE: Running High Fidelity Servers on Linux


* Launch a new host/instance

Sign up with https://www.digitalocean.com/

[[https://www.digitalocean.com/community/tutorials/how-to-use-ssh-keys-with-digitalocean-droplets][Upload an ssh key]].

Create a [[https://www.digitalocean.com/community/tutorials/how-to-create-your-first-digitalocean-droplet-virtual-server][droplet]].  "Ubuntu 17.04 x64, 2 GB Memory / 40 GB Disk"
works well.  The next size down can also work, though it will become
overloaded if a few people visit the domain at once.

Visit digitalocean's [[https://cloud.digitalocean.com/droplets][droplets]] page and discover the ip address of
your new host.  Whenever you see ~x.x.x.x~ below, use the ip address.

* Create a non-root user

Log into the new host.  Make a non-root account and copy root's ssh
public keys into it.  Give the new account sudo rights with [[https://www.digitalocean.com/community/tutorials/how-to-create-a-sudo-user-on-ubuntu-quickstart][usermod]].

#+BEGIN_SRC
ssh root@x.x.x.x
adduser hifi
cp -r ~root/.ssh ~hifi/.ssh
chown -R hifi:hifi ~hifi/.ssh
usermod -aG sudo hifi
exit
#+END_SRC

Log into the new host as the non-root user.  Install the prerequisites
for building High Fidelity's servers.

#+BEGIN_SRC
ssh hifi@x.x.x.x
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install build-essential libssl-dev cmake
sudo apt-get install qt*5-dev libqt5quick5 libqt5websockets5-dev
#+END_SRC

* Checkout High Fidelity's source and build

#+BEGIN_SRC
git clone https://github.com/highfidelity/hifi.git
cd hifi
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DSERVER_ONLY=TRUE ..
make -j2
#+END_SRC

* Set up systemd files

#+BEGIN_SRC
sudo su
mkdir -p /var/log/hifi/
#+END_SRC

#+BEGIN_SRC
cat > /etc/systemd/system/domain-server.service <<EOF
[Unit]
Description=Domain Server service for High Fidelity
After=network.target
[Service]
Restart=on-failure
WorkingDirectory=/home/hifi/hifi/build/domain-server
ExecStart=/bin/bash -c 'ulimit -c unlimited; /home/hifi/hifi/build/domain-server/domain-server 2>&1 >>  /var/log/hifi/domain-server.log'
[Install]
WantedBy=multi-user.target
EOF
#+END_SRC

#+BEGIN_SRC
cat > /etc/systemd/system/assignment-client.service <<EOF
[Unit]
Description=Assignment client service for High Fidelity server
After=network.target
PartOf=assignment-clients.target
[Service]
Restart=always
Environment="LD_LIBRARY_PATH=/home/hifi/hifi/build/ext/makefiles/nvtt/project/lib/"
WorkingDirectory=/home/hifi/hifi/build/assignment-client
ExecStart=/bin/bash -c 'ulimit -c unlimited; /home/hifi/hifi/build/assignment-client/assignment-client -n7 2>&1 >> /var/log/hifi/assignment-client.log'
[Install]
WantedBy=assignment-clients.target
EOF
#+END_SRC

* Run the servers

#+BEGIN_SRC
systemctl start domain-server
systemctl start assignment-client
#+END_SRC

* Adjust server settings

Visit the domain-server page: http://x.x.x.x:40100/ and add a password (don't use a password that's
in use elsewhere).
