* Building a Clock for High Fidelity

A clock for High Fidelity has several parts: A model for the body of
the clock (including a texture for the face), a model for each hand, a
server-side script to update the hands, and a client-side script to
rez the clock.  I'll walk through each part and explain what was done;
the result is in the [[https://github.com/sethalves/hifi-content/tree/master/clock][clock source]].  The actual commands used for the
recipe can be seen by running make on the [[https://github.com/sethalves/hifi-content/blob/master/clock/Makefile][Makefile]].

** Body

OpenSCAD has a cylinder primative (see [[http://www.openscad.org/cheatsheet/][cheatsheet]]), and one of the
parameters is [[https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Other_Language_Features#.24fa.2C_.24fs_and_.24fn][how many segments]] will make up the circles at the ends.
This allows an easy way to create some dodecagons:

#+BEGIN_SRC
cylinder(h=0.08, r1=0.5, r2=0.5, center=true, $fn=12);
#+END_SRC

The face of the clock should face upward (positive-y in High Fidelity), so the scad file has

#+BEGIN_SRC
rotate([-90, 0, 0]) { ... }
#+END_SRC

and the face of the clock should be in positive x and z space, because
that's what ~wavefront-obj-tool~ expects when it maps a texture onto a
model.  The face is put into position with

#+BEGIN_SRC
translate([0.45, 0, 0.45]) { ... }
#+END_SRC

In the ~Makefile~ is a rule to process the ~clock.scad~ file and
export ~clock.stl~.  High Fidelity doesn't support [[https://en.wikipedia.org/wiki/STL_(file_format)][STL model files]],
but it's easy to convert from STL to [[https://en.wikipedia.org/wiki/Wavefront_.obj_file][OBJ]] with ~wavefront-obj-tool~.

The image for the face of the clock is made by starting with a blank
(white) png image from ~pbmmake~ (of [[http://netpbm.sourceforge.net/][Netpbm]]):

#+BEGIN_SRC
pbmmake -white 480 480 | pnmtopng > clock-face-blank.png
#+END_SRC

and then drawing numbers in a circle with ~convert~ from [[https://www.imagemagick.org/script/convert.php][ImageMagick]].

#+BEGIN_SRC
convert -pointsize 40 -fill black
  -draw 'text 320,94 "1"'
  -draw 'text 386,160 "2"'
  ...
  -draw 'text 210,70 "12"'
#+END_SRC

The face texture is applied to the clock's model with:

#+BEGIN_SRC
wavefront-obj-tool clock-untextured.obj -o clock-offset.obj
	-U -M 0.9 0.9
	-L clock.mtl -S clock_face_mtl
#+END_SRC

This reads in ~clock-untextured.obj~ and maps a texture from the top
down onto the model.  ~-M 0.9 0.9~ means that the texture should be
stretched to cover a square in the xz plane from (0, 0) to (0.9, 0.9).
This is the bounding size in model space of the clock face, as seen
from above.  The ~-U~ argument means that only upward-facing (normal
has positive y) faces should have their material set.  OBJ files have
their [[https://en.wikipedia.org/wiki/Wavefront_.obj_file#Referencing_materials][material specifications]] in a separate file.  These material
files are usually found next to (in the same directory as) the OBJ
files that refer to them.  The ~-L clock.mtl -S clock_face_mtl~
arguments set the name of the material file and the name of the
material, respectively.  An mtl file can hold more than one material
definition -- each has its own name.

If you've run the Makefile, you can see the resulting model with
meshlab

#+BEGIN_SRC
meshlab clock.obj
#+END_SRC

Meshlab has many options under the ~Render~ menu which can be enabled
to check that the model is consistent and water-tight.  It can also
show the model-space axis so it's possible to confirm that the model
is oriented as expected.

The final step in the creation of the OBJ model files is to [[https://www.gnu.org/software/gzip/manual/][gzip]] them.
~interface~ will recognize a file that ends in ~.obj.gz~ and
uncompress it before reading.  OBJ is a plain-text format and
the files can be quite large for models with many triangles.

** Hands

OpenSCAD is also used for the clock hands. In the repository
are two files: ~hour-hand.scad~ and ~minute-hand.scad~.  Each contains
a single OpenSCAD [[https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Primitive_Solids#polyhedron][polyhedron]] statement.  They produce stretched tetrahedrons
of different lengths, and these will serve as the hands of the clock.  Like
the clock body, they are both processed into STL and then OBJ files (though
they receive no texture).  Again, Meshlab can be used to examine the
intermediate and final model files.

** Rezzing

High Fidelity can run javascript programs in a [[https://wiki.highfidelity.com/wiki/Script_Types_Overview][variety]] of places:
  - Interface can load a script from a url: This script will be
    running on the client, and wont necessarily be running in the
    clients of other avatars.
  - Interface can run an entity script: [[https://wiki.highfidelity.com/wiki/Entity][Entities]] have a [[https://wiki.highfidelity.com/wiki/EntityItemProperties][property]]
    called ~script~ which can be the url of a script. Any Interface
    that is told about this entity will download and run the script.
    Every client who is present will have its own copy of that script
    running, independently.
  - Scripted Agent: A domain can run an assignment-client (server)
    which act like a headless version of Interface. This usually
    causes an avatar to appear in-world, and the AC can run a script
    much like Interface can.
  - Server Script: In addition to their ~script~ property, Entities
    have a ~serverScripts~ property which will cause an
    assignment-client to run the script, even without any agents
    (Interface or Agent ACs) present.  Only one copy of such a script
    will be running, regardless of how many avatars visit the area.


The clock's [[https://github.com/sethalves/hifi-content/blob/master/clock/rez-clock.js][rez script]] is the first kind.  It's run from ~interface~
by open the ~Running Scripts~ dialog and selecting ~from url~ or ~from
disk~.  It calls ~Entities.addEntity~ once for the clock body and once
for each clock hand.  The hour-hand and minute-hand Entities
/children/ of the clock body.  Rather than a world-frame ~position~
and ~rotation~, they are given ~localPosition~ and ~localRotation~ and
a ~parentID~ set to the ID of the clock.  This means that when the
clock moves, the hands will go along with it.  The hands are also
given a non-default ~registrationPoint~.  The ~registrationPoint~ is a
vector that defines a position within the local bounding-box of the
model.  The default is ~{ x: 0.5, y: 0.5, z: 0.5 }~, meaning the
center of the bounding-box.  This rez script sets each
~registrationPoint~ to ~{ x: 0.5, y: 0.0, z: 0.0 }~.  This causes the
center of rotation for the hand entities to be down at the thick end
of the hands.

At the end of the rez script, a Server Script is added to the clock
with ~Entities.editEntity~.  This edit also updates the clocks
~userData~ property to encode the IDs of the clock hands.

** Script

The clock uses the server [[https://github.com/sethalves/hifi-content/blob/master/clock/clock.js][script]] (clock.js) to update the hands about
once per minute.  In the script, ~preload~ is the first thing to be
called, and will have, as an argument, the [[https://en.wikipedia.org/wiki/Universally_unique_identifier][UUID]] of the entity whose
~serverScripts~ property caused this script to be run.  This script is
only given the entityID of the main clock body, and needs to know the
entityIDs of the clock hands.  It expects these IDs to be stored in
the ~userData~ property of the clock.

Once per minute it gets the current (UTC) time and does a bit of math,
before calling ~Entities.editEntity~ on each hand.  The edits change
the ~localRotation~ property, causing the hands to rotate relative to
the clock body.

** Hosting

To be used by a High Fidelity server, all these model and script files need to be
available over the network.  There are 3 main places for these types of files:
  - local filesystem of a user's computer
  - a webserver
  - a [[https://wiki.highfidelity.com/wiki/Asset_Server_(ATP)][High Fidelity asset-server]]

A script on a user's local filesystem can be loaded by that user's
~interface~, but wont be of any use to servers (assuming the servers
aren't also running on the local computer) or to other users.  A
webserver is a good option, but setting up a webserver on the greater
internet isn't easy.  Hifi's asset-server is a good choice, because
once a hifi domain is up and running, the asset-server is already
configured and ready.

The files need to be copied from the local build diretory to the
asset-server.  One way is to launch ~interface~ and use the ~Asset
Browser~ dialog to upload each of the needed files: clock.obj.gz,
clock.mtl, clock-face.png, rez-clock.js, hour-hand.obj.gz,
minute-hand.obj.gz, clock.js.  Notice that ~rez-clock.js~ is missing
from this list -- client scripts can't be run from an asset-server
(though they can be run from a web-server).  The reason is that
the meaning of the url ~atp:/rez-clock~ is going to be different
for different domains.

Another way to upload these files is ~atp-client~, found in
the tools directory in the [[https://github.com/highfidelity/hifi][main High Fidelity repository]].  If you
built the software on Linux, it should be in the build directory:
~build/tools/atp-client/atp-client~.  This tool can be used to (among
other things) upload files to an asset-server.

#+BEGIN_SRC
./atp-client -u <<username>>:<<password>> -T clock.obj.gz atp://eschatology-dev/clock/clock.obj.gz
#+END_SRC

The clock's ~Makefile~ has a target called ~upload-atp~ which will use
~atp-client~ to upload the files.  Before this will work, the
~ATP_CLIENT~ near the top of the ~Makefile~ will need to be correctly
set, and the user will need to have write-permissions for the
asset-server.

Notice this other form of ATP URL -- it includes the domain-name along
with the path.  atp-client supports these, but ~interface~ and the
script-server don't (yet?) allow cross-domain ATP urls, they only
accept the shorter form.

** Rezzing

Finally, once the files are created and placed on the domain's
asset-server, connect to the domain with ~interface~ and open the
~Running Scripts~ dialog.  Use the ~from file~ button and navigate to
and select ~rez-clock.js~ script.  If all goes well, the clock should
appear in front of the avatar.  This script runs once and then stops.
If it's reloaded, it will make a new clock.  Once the clock is
created, the script can be deleted from the ~Running Scripts~ list.
Using the local filesystem for the rez script works, because it
just needs to be run once, by the local ~interface~.  No server
or other user needs to run it.

** Bugs

As of this writing, there is a bug that will keep ~clock.js~ from
updating the hands of the clock until the interface that rezzed the
clock leaves the domain.  So, once the clock is rezzed, log out and
then back in to see it work.
